source $HOME/.config/nvim/settings/plugins.vim
source $HOME/.config/nvim/settings/general.vim
source $HOME/.config/nvim/settings/themes/lightline.vim
source $HOME/.config/nvim/settings/themes/gruvbox.vim
source $HOME/.config/nvim/settings/plugins/rainbow.vim
source $HOME/.config/nvim/settings/plugins/denite.vim
source $HOME/.config/nvim/settings/plugins/deoplete.vim
source $HOME/.config/nvim/settings/plugins/multiple_cursors.vim
source $HOME/.config/nvim/settings/utils.vim
